services:
  # Build the app services
  auth:
    build: auth
    ports:
     - 4128:4128
  frontend:
    build: frontend
    ports:
     - 3000:3000
  backend:
    build: backend
    ports:
      - 3300:3300

