services:
  # Build the app services
  backend:
    build: backend
    ports:
      - 3300:3300
  frontend:
    build: frontend
  nginx:
    container_name: nginx
    build: nginx
    # Bind the port 80 of container to machine port 80
    ports:
      - 3000:3000
    # Make app as nginx dependency service
    depends_on:
      - backend